[window]
decorations = "None"
opacity = 1
startup_mode = "Fullscreen"
padding = { x = 4, y = 28 }

[font]
size = 15

[selection]
save_to_clipboard = true

# Colors (Ayu Dark)

# Default colors
#[colors.primary]
#background = '#0A0A0A'
#foreground = '#B3B1AD'

# Normal colors
#[colors.normal]
#black   = '#01060E'
#red     = '#EA6C73'
#green   = '#91B362'
#yellow  = '#F9AF4F'
#blue    = '#53BDFA'
#magenta = '#FAE994'
#cyan    = '#90E1C6'
#white   = '#C7C7C7'

## Bright colors
#[colors.bright]
#black   = '#686868'
#red     = '#F07178'
#green   = '#C2D94C'
#yellow  = '#FFB454'
#blue    = '#59C2FF'
#magenta = '#FFEE99'
#cyan    = '#95E6CB'
#white   = '#FFFFFF'

[colors.primary]
# hard contrast: 
background = '0x1d2021'
# regular contrast: background= '0x282828'
# soft contrast: background = '0x32302f'
foreground = '0xebdbb2'

[colors.normal]
black = '0x282828'
red = '0xcc241d'
green = '0x98971a'
yellow = '0xd79921'
blue = '0x458588'
magenta = '0xb16286'
cyan = '0x689d6a'
white = '0xa89984'

[colors.bright]
black = '0x928374'
red = '0xfb4934'
green = '0xb8bb26'
yellow = '0xfabd2f'
blue = '0x83a598'
magenta = '0xd3869b'
cyan = '0x8ec07c'
white = '0xebdbb2'
