import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]

[window]
decorations = "None"
opacity = 1
startup_mode = "Maximized"
padding = { x = 10, y = 4 }

[font]
size = 12
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[selection]
save_to_clipboard = true

[shell]
program = '/home/nooodlesoup/.cargo/bin/nu'
args = ["-e zellij"]

