#!/bin/sh
WORKSPACE=$(hyprctl activewindow -j | jq .workspace.name | awk -F'"' '{print $3}' | awk -F'\' '{print $1}')
WINDOW=$(hyprctl activewindow -j | jq .class | awk -F'"' '{print $2}')

echo "$WORKSPACE : $WINDOW" 
